# Generated by Django 3.2.4 on 2021-07-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
